apiVersion: v1
kind: ConfigMap
metadata:
  name: poodmaan-config
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: podcast_db
  DB_USER: postgres
  MINIO_ENDPOINT: minio
  MINIO_PORT: "9000"
  MINIO_USE_SSL: "false"
  MINIO_BUCKET: podcast-storage
  MINIO_PUBLIC_URL: http://localhost:30900
  ADMIN_API_URL: http://creator-studio:3001/api
---
apiVersion: v1
kind: Secret
metadata:
  name: poodmaan-secret
type: Opaque
stringData:
  DB_PASSWORD: postgres
  POSTGRES_PASSWORD: postgres
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: minioadmin
